//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public string Address_Line_1 { get; set; }
        public string Address_Line_2 { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public string Zip_Code { get; set; }
        public int Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
