//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public string Contact { get; set; }
        public int ID { get; set; }
    
        public virtual Address Address { get; set; }
    }
}
